import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

/// Guards the app against writing to a column Postgres generates.
///
/// `ipaq_results.activity_level` and `iqol_results.iqol_score` are GENERATED
/// columns in the live database. Postgres rejects any insert that supplies a
/// value for one:
///
///   cannot insert a non-DEFAULT value into column "activity_level"
///   SQLSTATE 428C9
///
/// saveIpaq sent `activity_level` on every submission, so IPAQ could never be
/// saved by anyone — the screen showed "Your answers could not be saved" and
/// the patient was stuck, because the route guard will not advance past IPAQ
/// until a row exists. saveIqol had the same defect waiting behind it.
///
/// This is a source-level assertion rather than a round trip through a fake
/// Supabase, which the notifier's use of `Supabase.instance.client` does not
/// allow without an HTTP harness this suite has no other use for. It is worth
/// having anyway: the failure it prevents is invisible in review — the payload
/// looks perfectly reasonable — and only shows up against the real database.
void main() {
  /// Column names the database computes. Adding a value for any of these to an
  /// insert payload breaks that questionnaire outright.
  const generatedColumns = <String, String>{
    'activity_level': 'ipaq_results',
    'iqol_score': 'iqol_results',
  };

  test('no insert payload supplies a generated column', () {
    final source = File(
      'lib/features/assessment/notifiers/assessment_summary_notifier.dart',
    ).readAsStringSync();

    generatedColumns.forEach((column, table) {
      expect(
        source,
        isNot(contains("'$column':")),
        reason:
            '$table.$column is generated by Postgres, which rejects an insert '
            'that supplies a value for it (SQLSTATE 428C9). Remove it from the '
            'payload and let the database derive it.',
      );
    });
  });

  test('the columns are still recomputed on the way back out', () {
    // Dropping them from the payload is only safe because nothing reads them
    // back: both models derive the value from the answers they restore.
    final ipaq = File(
      'lib/features/assessment/models/ipaq_model.dart',
    ).readAsStringSync();
    expect(
      ipaq,
      contains('restored.computedActivityLevel'),
      reason:
          'IPAQModel.fromSupabaseRow must recompute the classification, '
          'since activity_level is never selected back into the model.',
    );

    final iqol = File(
      'lib/features/assessment/models/iqol_model.dart',
    ).readAsStringSync();
    expect(
      iqol,
      isNot(contains("row['iqol_score']")),
      reason:
          'IQOLModel derives score from the restored items; reading the '
          'generated column back would give two sources of truth.',
    );
  });
}
